project:
  type: website
  output-dir: docs

website:
  title: "Kelly Ahern's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: school.qmd
        text: Education
      - href: Fire project.qmd
        text: Fire Project
      - href: Experience.qmd
        text: Work Experience
      - about.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: source

